# Generated by Django 4.0 on 2021-12-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('city', models.IntegerField(default=1, null=True, verbose_name='city')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shifts.location', verbose_name='location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='auth.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'userLocation',
                'verbose_name_plural': 'userLocations',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(auto_now_add=True, verbose_name='date_from')),
                ('date_until', models.DateTimeField(blank=True, null=True, verbose_name='date_until')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=15, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=15, verbose_name='longitude')),
                ('worked_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='auth.user', verbose_name='user')),
                ('user_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='shifts.userlocation', verbose_name='user_location')),
            ],
            options={
                'verbose_name': 'record',
                'verbose_name_plural': 'records',
                'ordering': ['date_from'],
            },
        ),
    ]
