# Generated by Django 4.0 on 2021-12-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='record',
            name='longitude',
        ),
        migrations.AddField(
            model_name='record',
            name='checkin_latitude',
            field=models.DecimalField(decimal_places=45, default=-20, max_digits=50, verbose_name='check in latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='checkin_longitude',
            field=models.DecimalField(decimal_places=45, default=-20, max_digits=50, verbose_name='check in longitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='checkout_latitude',
            field=models.DecimalField(decimal_places=45, default=-20, max_digits=50, verbose_name='check out latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='checkout_longitude',
            field=models.DecimalField(decimal_places=45, default=-20, max_digits=50, verbose_name='check out longitude'),
            preserve_default=False,
        ),
    ]
