# Generated by Django 4.0 on 2021-12-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_remove_record_latitude_remove_record_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='checkin_latitude',
            field=models.DecimalField(decimal_places=9, max_digits=50, verbose_name='check in latitude'),
        ),
        migrations.AlterField(
            model_name='record',
            name='checkin_longitude',
            field=models.DecimalField(decimal_places=9, max_digits=50, verbose_name='check in longitude'),
        ),
        migrations.AlterField(
            model_name='record',
            name='checkout_latitude',
            field=models.DecimalField(decimal_places=9, max_digits=50, verbose_name='check out latitude'),
        ),
        migrations.AlterField(
            model_name='record',
            name='checkout_longitude',
            field=models.DecimalField(decimal_places=9, max_digits=50, verbose_name='check out longitude'),
        ),
    ]
