# Generated by Django 4.0 on 2021-12-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_record_checkin_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='checkin_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='check in address'),
        ),
        migrations.AddField(
            model_name='record',
            name='checkout_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='check in address'),
        ),
    ]
