# Generated by Django 4.0 on 2022-01-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_record_checkin_address_record_checkout_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='hour_value',
            field=models.IntegerField(default=12, null=True, verbose_name='city'),
        ),
    ]
