# Generated by Django 4.0 on 2022-01-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_alter_record_checkin_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='checkin_address',
        ),
    ]
