# Generated by Django 4.0 on 2022-01-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_remove_record_checkin_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='checkout_address',
        ),
    ]
