# Generated by Django 4.0 on 2022-01-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_remove_record_checkout_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='worked_hours',
        ),
    ]
