# Generated by Django 4.0 on 2022-01-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_remove_record_worked_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='new_worked_hours',
            field=models.DateTimeField(blank=True, null=True, verbose_name='worked_hours'),
        ),
    ]
