# Generated by Django 4.0 on 2022-01-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_record_new_worked_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='new_worked_hours',
            new_name='worked_hours',
        ),
    ]
