# Generated by Django 4.0 on 2022-01-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_rename_new_worked_hours_record_worked_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='worked_hours',
        ),
    ]
