# Generated by Django 4.0 on 2022-01-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0012_remove_record_worked_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='worked_hours',
            field=models.DurationField(blank=True, null=True, verbose_name='worked_hours'),
        ),
    ]
